# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb34dc7aac9f44f4ca94e5d7e5ceadad04a9f02b3c94dc64aba5201159aaa47265ffde74ed0abeb3e60ea6caba9edcc717c7ea21adbd6ce0582c1571611dae58

test:
  secret_key_base: 0de203a85a8298a8d27a0e55fd29d9a62f4946a6e9c62c2a060dedf88a537968e157dc36a797b7994f0e8641ba72fdedd35d4ea03dfbcf9278a1afbb77b65de4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
